// <auto-generated />
using System;
using BankUrun.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankUrun.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709085545_AddOrganizationAndScores")]
    partial class AddOrganizationAndScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankUrun.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_name");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("branch_code");

                    b.Property<string>("BranchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("branch_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_code_not_blank", "length(btrim(branch_code)) > 0");

                            t.HasCheckConstraint("ck_branches_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_branches_type", "branch_type in ('Karma', 'Kurumsal', 'Ticari')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("BranchId", "UnitId")
                        .IsUnique();

                    b.ToTable("branch_units", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GroupNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("group_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GroupNo")
                        .IsUnique();

                    b.ToTable("group_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_definitions_group_no_not_blank", "length(btrim(group_no)) > 0");

                            t.HasCheckConstraint("ck_group_definitions_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupProductScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DevelopmentShare")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("development_share");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<decimal>("HgoShare")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("hgo_share");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("score");

                    b.Property<decimal>("SizeShare")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("size_share");

                    b.Property<int>("SubProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_instance_id");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SubProductInstanceId");

                    b.HasIndex("GroupId", "SubProductInstanceId")
                        .IsUnique();

                    b.ToTable("group_product_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_product_scores_development_share_range", "development_share between 0 and 1");

                            t.HasCheckConstraint("ck_group_product_scores_hgo_share_range", "hgo_share between 0 and 1");

                            t.HasCheckConstraint("ck_group_product_scores_score_non_negative", "score >= 0");

                            t.HasCheckConstraint("ck_group_product_scores_size_share_range", "size_share between 0 and 1");

                            t.HasCheckConstraint("ck_group_product_scores_target_non_negative", "target_value >= 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("GroupId", "UnitId")
                        .IsUnique();

                    b.ToTable("group_units", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId", "ProductDefinitionType");

                    b.HasIndex("MainProductId", "Year", "Term")
                        .IsUnique();

                    b.ToTable("main_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_instances_term_range", "term between 1 and 12");

                            t.HasCheckConstraint("ck_main_product_instances_type", "product_definition_type = 'Main'");

                            t.HasCheckConstraint("ck_main_product_instances_year_range", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("product_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_definitions_code_format", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_product_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_definitions_type", "product_type in ('Main', 'Sub')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_instance_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.HasKey("Id");

                    b.HasIndex("MainProductInstanceId", "SubProductId")
                        .IsUnique();

                    b.HasIndex("SubProductId", "ProductDefinitionType");

                    b.ToTable("sub_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_sub_product_instances_type", "product_definition_type = 'Sub'");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.UnitDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("UnitNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("unit_no");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("UnitNo")
                        .IsUnique();

                    b.ToTable("unit_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_unit_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_unit_definitions_unit_no_not_blank", "length(btrim(unit_no)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchUnit", b =>
                {
                    b.HasOne("BankUrun.Web.Models.Branch", "Branch")
                        .WithMany("BranchUnits")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.UnitDefinition", "Unit")
                        .WithMany("BranchUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupProductScore", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("GroupProductScores")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.SubProductInstance", "SubProductInstance")
                        .WithMany("GroupProductScores")
                        .HasForeignKey("SubProductInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("SubProductInstance");
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupUnit", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("GroupUnits")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.UnitDefinition", "Unit")
                        .WithMany("GroupUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "MainProduct")
                        .WithMany("MainProductInstances")
                        .HasForeignKey("MainProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductInstance", "MainProductInstance")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("MainProductInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "SubProduct")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("SubProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductInstance");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.Navigation("BranchUnits");
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupDefinition", b =>
                {
                    b.Navigation("GroupProductScores");

                    b.Navigation("GroupUnits");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Navigation("SubProductInstances");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Navigation("MainProductInstances");

                    b.Navigation("SubProductInstances");
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.Navigation("GroupProductScores");
                });

            modelBuilder.Entity("BankUrun.Web.Models.UnitDefinition", b =>
                {
                    b.Navigation("BranchUnits");

                    b.Navigation("GroupUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
