// <auto-generated />
using System;
using BankUrun.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankUrun.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707192525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankUrun.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_name");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<string>("MainProductType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("main_product_type");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId", "MainProductType");

                    b.HasIndex("MainProductId", "Year", "Term")
                        .IsUnique();

                    b.ToTable("main_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_instances_term_range", "term between 1 and 12");

                            t.HasCheckConstraint("ck_main_product_instances_type", "main_product_type = 'Main'");

                            t.HasCheckConstraint("ck_main_product_instances_year_range", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("product_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_definitions_code_format", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_product_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_definitions_type", "product_type in ('Main', 'Sub')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_instance_id");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.Property<string>("SubProductType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("sub_product_type");

                    b.HasKey("Id");

                    b.HasIndex("MainProductInstanceId", "SubProductId")
                        .IsUnique();

                    b.HasIndex("SubProductId", "SubProductType");

                    b.ToTable("sub_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_sub_product_instances_type", "sub_product_type = 'Sub'");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "MainProduct")
                        .WithMany("MainProductInstances")
                        .HasForeignKey("MainProductId", "MainProductType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductInstance", "MainProductInstance")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("MainProductInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "SubProduct")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("SubProductId", "SubProductType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductInstance");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Navigation("SubProductInstances");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Navigation("MainProductInstances");

                    b.Navigation("SubProductInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
