// <auto-generated />
using System;
using BankUrun.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankUrun.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707120318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankUrun.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_name");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("MainProductId", "PeriodId")
                        .IsUnique();

                    b.ToTable("main_product_periods", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Term")
                        .IsUnique();

                    b.ToTable("periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_periods_term_range", "term between 1 and 12");

                            t.HasCheckConstraint("ck_periods_year_range", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_code_format", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_products_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MainProductPeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_period_id");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.HasKey("Id");

                    b.HasIndex("SubProductId");

                    b.HasIndex("MainProductPeriodId", "SubProductId")
                        .IsUnique();

                    b.ToTable("sub_product_assignments", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductPeriod", b =>
                {
                    b.HasOne("BankUrun.Web.Models.Product", "MainProduct")
                        .WithMany("MainProductPeriods")
                        .HasForeignKey("MainProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.Period", "Period")
                        .WithMany("MainProductPeriods")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProduct");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductAssignment", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductPeriod", "MainProductPeriod")
                        .WithMany("SubProductAssignments")
                        .HasForeignKey("MainProductPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.Product", "SubProduct")
                        .WithMany("SubProductAssignments")
                        .HasForeignKey("SubProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductPeriod");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductPeriod", b =>
                {
                    b.Navigation("SubProductAssignments");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Period", b =>
                {
                    b.Navigation("MainProductPeriods");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Product", b =>
                {
                    b.Navigation("MainProductPeriods");

                    b.Navigation("SubProductAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
