// <auto-generated />
using System;
using BankUrun.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankUrun.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718112857_UseStablePortfolioSubProductMetrics")]
    partial class UseStablePortfolioSubProductMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankUrun.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_name");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("branch_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_code_not_blank", "length(btrim(branch_code)) > 0");

                            t.HasCheckConstraint("ck_branches_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchMainProductExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EffectiveFromTerm")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from_term");

                    b.Property<int>("EffectiveFromYear")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from_year");

                    b.Property<int?>("EffectiveToTerm")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to_term");

                    b.Property<int?>("EffectiveToYear")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to_year");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId", "ProductDefinitionType");

                    b.HasIndex("BranchId", "MainProductId", "EffectiveFromYear", "EffectiveFromTerm")
                        .IsUnique();

                    b.ToTable("branch_main_product_exclusions", null, t =>
                        {
                            t.HasCheckConstraint("ck_branch_exclusions_from", "effective_from_year between 2000 and 2100 and effective_from_term in (1, 2)");

                            t.HasCheckConstraint("ck_branch_exclusions_to", "(effective_to_year is null and effective_to_term is null) or (effective_to_year between 2000 and 2100 and effective_to_term in (1, 2) and (effective_to_year * 2 + effective_to_term) >= (effective_from_year * 2 + effective_from_term))");

                            t.HasCheckConstraint("ck_branch_exclusions_type", "product_definition_type = 'Main'");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BranchPerformanceEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("branch_performance_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GroupNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("group_no");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("MiyPerformanceEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("miy_performance_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<bool>("ScaleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("scale_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GroupNo")
                        .IsUnique();

                    b.ToTable("group_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_definitions_group_no_not_blank", "length(btrim(group_no)) > 0");

                            t.HasCheckConstraint("ck_group_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_group_definitions_type", "group_type in ('Karma', 'Kurumsal', 'Ticari', 'Kobi', 'Diger')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId", "ProductDefinitionType");

                    b.HasIndex("MainProductId", "Year", "Term")
                        .IsUnique();

                    b.ToTable("main_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_instances_term_range", "term in (1, 2)");

                            t.HasCheckConstraint("ck_main_product_instances_type", "product_definition_type = 'Main'");

                            t.HasCheckConstraint("ck_main_product_instances_year_range", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("calculation_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("CriterionScore")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("criterion_score");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MainProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_instance_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MainProductInstanceId");

                    b.HasIndex("GroupId", "MainProductInstanceId")
                        .IsUnique();

                    b.ToTable("main_product_parameters", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_parameters_calculation_type", "calculation_type in ('Average', 'Cumulative')");

                            t.HasCheckConstraint("ck_main_product_parameters_criterion_score", "criterion_score >= 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<int>("PortfolioTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_type_id");

                    b.Property<int>("ProductGamutId")
                        .HasColumnType("integer")
                        .HasColumnName("product_gamut_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PortfolioTypeId");

                    b.HasIndex("BranchId", "GroupId");

                    b.HasIndex("BranchId", "ProductGamutId");

                    b.HasIndex("ProductGamutId", "GroupId");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_code", "code ~ '^P[A-Z0-9]+-[A-Z0-9]{2}[0-9]{2}$'");

                            t.HasCheckConstraint("ck_portfolios_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.PortfolioMainProductMonthlyTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("MainProductParameterId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_parameter_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MainProductParameterId", "GroupId");

                    b.HasIndex("PortfolioId", "GroupId");

                    b.HasIndex("PortfolioId", "MainProductParameterId", "Month")
                        .IsUnique();

                    b.ToTable("portfolio_main_product_monthly_targets", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_targets_month", "month between 1 and 12");

                            t.HasCheckConstraint("ck_portfolio_targets_value", "target_value >= 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.PortfolioSubProductMonthlyMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_as_of_date");

                    b.Property<decimal?>("ActualValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("SubProductId", "ProductDefinitionType");

                    b.HasIndex("PortfolioId", "SubProductId", "Year", "Term", "Month")
                        .IsUnique();

                    b.ToTable("portfolio_sub_product_monthly_metrics", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_sub_metrics_actual_pair", "(actual_value is null and actual_as_of_date is null) or (actual_value is not null and actual_as_of_date is not null)");

                            t.HasCheckConstraint("ck_portfolio_sub_metrics_month", "month between 1 and 12");

                            t.HasCheckConstraint("ck_portfolio_sub_metrics_term", "term in (1, 2)");

                            t.HasCheckConstraint("ck_portfolio_sub_metrics_type", "product_definition_type = 'Sub'");

                            t.HasCheckConstraint("ck_portfolio_sub_metrics_value", "actual_value is null or actual_value >= 0");

                            t.HasCheckConstraint("ck_portfolio_sub_metrics_year", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.PortfolioType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("portfolio_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_types_code", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_portfolio_types_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("product_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_definitions_code_format", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_product_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_definitions_type", "product_type in ('Main', 'Sub')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductGamut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Code")
                        .IsUnique();

                    b.ToTable("product_gamuts", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_gamuts_code", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_product_gamuts_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductGamutMainProductAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EffectiveFromTerm")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from_term");

                    b.Property<int>("EffectiveFromYear")
                        .HasColumnType("integer")
                        .HasColumnName("effective_from_year");

                    b.Property<int?>("EffectiveToTerm")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to_term");

                    b.Property<int?>("EffectiveToYear")
                        .HasColumnType("integer")
                        .HasColumnName("effective_to_year");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("ProductGamutId")
                        .HasColumnType("integer")
                        .HasColumnName("product_gamut_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId", "ProductDefinitionType");

                    b.HasIndex("ProductGamutId", "MainProductId", "EffectiveFromYear", "EffectiveFromTerm")
                        .IsUnique();

                    b.ToTable("product_gamut_main_product_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_gamut_assignments_from", "effective_from_year between 2000 and 2100 and effective_from_term in (1, 2)");

                            t.HasCheckConstraint("ck_gamut_assignments_to", "(effective_to_year is null and effective_to_term is null) or (effective_to_year between 2000 and 2100 and effective_to_term in (1, 2) and (effective_to_year * 2 + effective_to_term) >= (effective_from_year * 2 + effective_from_term))");

                            t.HasCheckConstraint("ck_gamut_assignments_type", "product_definition_type = 'Main'");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_instance_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.HasKey("Id");

                    b.HasIndex("MainProductInstanceId", "SubProductId")
                        .IsUnique();

                    b.HasIndex("SubProductId", "ProductDefinitionType");

                    b.ToTable("sub_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_sub_product_instances_type", "product_definition_type = 'Sub'");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("Branches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchMainProductExclusion", b =>
                {
                    b.HasOne("BankUrun.Web.Models.Branch", "Branch")
                        .WithMany("MainProductExclusions")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "MainProduct")
                        .WithMany("BranchExclusions")
                        .HasForeignKey("MainProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "MainProduct")
                        .WithMany("MainProductInstances")
                        .HasForeignKey("MainProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductParameter", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("MainProductParameters")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.MainProductInstance", "MainProductInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("MainProductInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MainProductInstance");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Portfolio", b =>
                {
                    b.HasOne("BankUrun.Web.Models.PortfolioType", "PortfolioType")
                        .WithMany("Portfolios")
                        .HasForeignKey("PortfolioTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.Branch", "Branch")
                        .WithMany("Portfolios")
                        .HasForeignKey("BranchId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductGamut", "ProductGamut")
                        .WithMany("Portfolios")
                        .HasForeignKey("ProductGamutId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("PortfolioType");

                    b.Navigation("ProductGamut");
                });

            modelBuilder.Entity("BankUrun.Web.Models.PortfolioMainProductMonthlyTarget", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductParameter", "MainProductParameter")
                        .WithMany("PortfolioMonthlyTargets")
                        .HasForeignKey("MainProductParameterId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.Portfolio", "Portfolio")
                        .WithMany("MainProductMonthlyTargets")
                        .HasForeignKey("PortfolioId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductParameter");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("BankUrun.Web.Models.PortfolioSubProductMonthlyMetric", b =>
                {
                    b.HasOne("BankUrun.Web.Models.Portfolio", "Portfolio")
                        .WithMany("SubProductMonthlyMetrics")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "SubProduct")
                        .WithMany("PortfolioMonthlyMetrics")
                        .HasForeignKey("SubProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductGamut", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("ProductGamuts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductGamutMainProductAssignment", b =>
                {
                    b.HasOne("BankUrun.Web.Models.ProductGamut", "ProductGamut")
                        .WithMany("MainProductAssignments")
                        .HasForeignKey("ProductGamutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "MainProduct")
                        .WithMany("ProductGamutAssignments")
                        .HasForeignKey("MainProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProduct");

                    b.Navigation("ProductGamut");
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductInstance", "MainProductInstance")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("MainProductInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "SubProduct")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("SubProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductInstance");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.Navigation("MainProductExclusions");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupDefinition", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("MainProductParameters");

                    b.Navigation("ProductGamuts");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("SubProductInstances");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductParameter", b =>
                {
                    b.Navigation("PortfolioMonthlyTargets");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Portfolio", b =>
                {
                    b.Navigation("MainProductMonthlyTargets");

                    b.Navigation("SubProductMonthlyMetrics");
                });

            modelBuilder.Entity("BankUrun.Web.Models.PortfolioType", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Navigation("BranchExclusions");

                    b.Navigation("MainProductInstances");

                    b.Navigation("PortfolioMonthlyMetrics");

                    b.Navigation("ProductGamutAssignments");

                    b.Navigation("SubProductInstances");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductGamut", b =>
                {
                    b.Navigation("MainProductAssignments");

                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
