// <auto-generated />
using System;
using BankUrun.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankUrun.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716111309_AddBranchSubProductMonthlyMetrics")]
    partial class AddBranchSubProductMonthlyMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankUrun.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_name");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("branch_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_code_not_blank", "length(btrim(branch_code)) > 0");

                            t.HasCheckConstraint("ck_branches_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchMainProductMonthlyMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_as_of_date");

                    b.Property<decimal?>("ActualValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_value");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("MainProductParameterId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_parameter_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "GroupId");

                    b.HasIndex("MainProductParameterId", "GroupId");

                    b.HasIndex("BranchId", "MainProductParameterId", "Month")
                        .IsUnique();

                    b.ToTable("branch_main_product_monthly_metrics", null, t =>
                        {
                            t.HasCheckConstraint("ck_branch_main_product_monthly_metrics_actual_pair", "(actual_value is null and actual_as_of_date is null) or (actual_value is not null and actual_as_of_date is not null)");

                            t.HasCheckConstraint("ck_branch_main_product_monthly_metrics_month", "month between 1 and 12");

                            t.HasCheckConstraint("ck_branch_main_product_monthly_metrics_values", "target_value >= 0 and (actual_value is null or actual_value >= 0)");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchSubProductMonthlyMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_as_of_date");

                    b.Property<decimal?>("ActualValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_value");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_value");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("SubProductId", "ProductDefinitionType");

                    b.HasIndex("BranchId", "SubProductId", "Year", "Term", "Month")
                        .IsUnique();

                    b.ToTable("branch_sub_product_monthly_metrics", null, t =>
                        {
                            t.HasCheckConstraint("ck_branch_sub_product_metrics_actual_pair", "(actual_value is null and actual_as_of_date is null) or (actual_value is not null and actual_as_of_date is not null)");

                            t.HasCheckConstraint("ck_branch_sub_product_metrics_month", "month between 1 and 12");

                            t.HasCheckConstraint("ck_branch_sub_product_metrics_term", "term in (1, 2)");

                            t.HasCheckConstraint("ck_branch_sub_product_metrics_type", "product_definition_type = 'Sub'");

                            t.HasCheckConstraint("ck_branch_sub_product_metrics_values", "target_value >= 0 and (actual_value is null or actual_value >= 0)");

                            t.HasCheckConstraint("ck_branch_sub_product_metrics_year", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BranchPerformanceEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("branch_performance_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GroupNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("group_no");

                    b.Property<string>("GroupSegment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_segment");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("MiyPerformanceEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("miy_performance_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<bool>("ScaleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("scale_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GroupNo")
                        .IsUnique();

                    b.ToTable("group_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_definitions_group_no_not_blank", "length(btrim(group_no)) > 0");

                            t.HasCheckConstraint("ck_group_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_group_definitions_segment", "group_segment in ('Karma', 'Kurumsal', 'Ticari', 'Kobi', 'Diger')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId", "ProductDefinitionType");

                    b.HasIndex("MainProductId", "Year", "Term")
                        .IsUnique();

                    b.ToTable("main_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_instances_term_range", "term between 1 and 12");

                            t.HasCheckConstraint("ck_main_product_instances_type", "product_definition_type = 'Main'");

                            t.HasCheckConstraint("ck_main_product_instances_year_range", "year between 2000 and 2100");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("calculation_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("CriterionScore")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("criterion_score");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MainProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_instance_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MainProductInstanceId");

                    b.HasIndex("GroupId", "MainProductInstanceId")
                        .IsUnique();

                    b.ToTable("main_product_parameters", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_parameters_calculation_type", "calculation_type in ('Average', 'Cumulative')");

                            t.HasCheckConstraint("ck_main_product_parameters_criterion_score", "criterion_score >= 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductSegmentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedScore")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allocated_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DevelopmentWeight")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("development_weight");

                    b.Property<decimal>("HgoWeight")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("hgo_weight");

                    b.Property<int>("MainProductParameterId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_parameter_id");

                    b.Property<string>("PerformanceSegment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("performance_segment");

                    b.Property<decimal>("ScaleShare")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("scale_share");

                    b.Property<decimal>("SizeShare")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("size_share");

                    b.Property<decimal>("SizeWeight")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("size_weight");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("TargetShare")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("target_share");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MainProductParameterId", "PerformanceSegment")
                        .IsUnique();

                    b.ToTable("main_product_segment_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_main_product_segment_rules_ratios", "target_share between 0 and 1 and size_share between 0 and 1 and scale_share between 0 and 1 and hgo_weight between 0 and 1 and development_weight between 0 and 1 and size_weight between 0 and 1");

                            t.HasCheckConstraint("ck_main_product_segment_rules_score", "allocated_score >= 0");

                            t.HasCheckConstraint("ck_main_product_segment_rules_segment", "performance_segment in ('Kurumsal', 'Ticari', 'Kobi', 'Bireysel', 'Diger')");

                            t.HasCheckConstraint("ck_main_product_segment_rules_sort_order", "sort_order > 0");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("product_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_definitions_code_format", "code ~ '^[A-Z0-9]{2}$'");

                            t.HasCheckConstraint("ck_product_definitions_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_definitions_type", "product_type in ('Main', 'Sub')");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MainProductInstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("main_product_instance_id");

                    b.Property<string>("ProductDefinitionType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("product_definition_type");

                    b.Property<int>("SubProductId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_product_id");

                    b.HasKey("Id");

                    b.HasIndex("MainProductInstanceId", "SubProductId")
                        .IsUnique();

                    b.HasIndex("SubProductId", "ProductDefinitionType");

                    b.ToTable("sub_product_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_sub_product_instances_type", "product_definition_type = 'Sub'");
                        });
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("Branches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchMainProductMonthlyMetric", b =>
                {
                    b.HasOne("BankUrun.Web.Models.Branch", "Branch")
                        .WithMany("MonthlyMetrics")
                        .HasForeignKey("BranchId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.MainProductParameter", "MainProductParameter")
                        .WithMany("MonthlyMetrics")
                        .HasForeignKey("MainProductParameterId", "GroupId")
                        .HasPrincipalKey("Id", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("MainProductParameter");
                });

            modelBuilder.Entity("BankUrun.Web.Models.BranchSubProductMonthlyMetric", b =>
                {
                    b.HasOne("BankUrun.Web.Models.Branch", "Branch")
                        .WithMany("SubProductMonthlyMetrics")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "SubProduct")
                        .WithMany("SubProductMonthlyMetrics")
                        .HasForeignKey("SubProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "MainProduct")
                        .WithMany("MainProductInstances")
                        .HasForeignKey("MainProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductParameter", b =>
                {
                    b.HasOne("BankUrun.Web.Models.GroupDefinition", "Group")
                        .WithMany("MainProductParameters")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.MainProductInstance", "MainProductInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("MainProductInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MainProductInstance");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductSegmentRule", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductParameter", "MainProductParameter")
                        .WithMany("SegmentRules")
                        .HasForeignKey("MainProductParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductParameter");
                });

            modelBuilder.Entity("BankUrun.Web.Models.SubProductInstance", b =>
                {
                    b.HasOne("BankUrun.Web.Models.MainProductInstance", "MainProductInstance")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("MainProductInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankUrun.Web.Models.ProductDefinition", "SubProduct")
                        .WithMany("SubProductInstances")
                        .HasForeignKey("SubProductId", "ProductDefinitionType")
                        .HasPrincipalKey("Id", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProductInstance");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("BankUrun.Web.Models.Branch", b =>
                {
                    b.Navigation("MonthlyMetrics");

                    b.Navigation("SubProductMonthlyMetrics");
                });

            modelBuilder.Entity("BankUrun.Web.Models.GroupDefinition", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("MainProductParameters");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductInstance", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("SubProductInstances");
                });

            modelBuilder.Entity("BankUrun.Web.Models.MainProductParameter", b =>
                {
                    b.Navigation("MonthlyMetrics");

                    b.Navigation("SegmentRules");
                });

            modelBuilder.Entity("BankUrun.Web.Models.ProductDefinition", b =>
                {
                    b.Navigation("MainProductInstances");

                    b.Navigation("SubProductInstances");

                    b.Navigation("SubProductMonthlyMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
